#!/bin/bash

#全局变量
phpfpmContainerName='marmot-phpfpm'
mysqlContainerName='marmot-mysql'

#加载公共smart函数库
. ./smartfunc/smartfunc
#加载mysql函数库
. ./smartfunc/mysqlfunc
#加载环境函数库
. ./smartfunc/environmentfunc
#加载phpfunc,php相关函数库
. ./smartfunc/phpfunc

case $1 in
'initial') 
	createDatabase $mysqlContainerName
	initialTestDatabase $mysqlContainerName
	initialDatabase $mysqlContainerName
	;;
'start')
	environmentStart
	;;
'stop')
	environmentStop
	;;
'upgrade')
	environmentUpgrade
	;;
'cbf')
	cbf $phpfpmContainerName
	;;
'composer')
	composer $phpfpmContainerName
	;;
'cs')
	cs $phpfpmContainerName
	;;
'cpd')
	cpd $phpfpmContainerName
	;;
'unit')
	unit $phpfpmContainerName
	;;
'unitFile')
	unitFile $phpfpmContainerName $2
	;;
'unitCover')
	unitCover $phpfpmContainerName
	;;
*)
	menu
esac


